modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "source and binary under BSD-3, assets under CC-BY-NC 4.0"
issueTrackerURL = "https://github.com/LocusAzzurro/Ultramarine/issues"

[[mods]]
modId = "ultramarine"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "${mod_icon}"
authors = "${mod_authors}"
credits = "${mod_credits}"
description = '''${mod_description}'''

[[dependencies.ultramarine]]
modId = "neoforge"
mandatory = true
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ultramarine]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"